// flow-typed signature: 76b980c5734aecc62990c1ceba107c1f
// flow-typed version: <<STUB>>/react-pixi-fiber_v^0.4.9/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pixi-fiber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pixi-fiber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pixi-fiber/cjs/react-pixi-alias.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-alias.production.min' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-fiber.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-fiber.production.min' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/react-pixi-alias' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/CustomPIXIComponent' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/index' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/inject' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/props' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/react-pixi-alias/index' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/ReactPixiFiber' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/render' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/types' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pixi-fiber/cjs/react-pixi-alias.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-alias.development'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-alias.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-alias.production.min'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-fiber.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-fiber.development'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-fiber.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-fiber.production.min'>;
}
declare module 'react-pixi-fiber/index' {
  declare module.exports: $Exports<'react-pixi-fiber'>;
}
declare module 'react-pixi-fiber/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber'>;
}
declare module 'react-pixi-fiber/react-pixi-alias.js' {
  declare module.exports: $Exports<'react-pixi-fiber/react-pixi-alias'>;
}
declare module 'react-pixi-fiber/src/CustomPIXIComponent.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/CustomPIXIComponent'>;
}
declare module 'react-pixi-fiber/src/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/index'>;
}
declare module 'react-pixi-fiber/src/inject.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/inject'>;
}
declare module 'react-pixi-fiber/src/props.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/props'>;
}
declare module 'react-pixi-fiber/src/react-pixi-alias/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/react-pixi-alias/index'>;
}
declare module 'react-pixi-fiber/src/ReactPixiFiber.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/ReactPixiFiber'>;
}
declare module 'react-pixi-fiber/src/render.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/render'>;
}
declare module 'react-pixi-fiber/src/Stage.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage'>;
}
declare module 'react-pixi-fiber/src/types.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/types'>;
}
declare module 'react-pixi-fiber/src/utils.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/utils'>;
}
